version: 2

models:
  - name: stg_customers
    description: "Cleaned customer data from raw source"
    columns:
      - name: customer_id
        description: "Primary key for customer"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Name of the customer"
        tests:
          - not_null
      - name: account_balance
        description: "Customer account balance"
        tests:
          - not_null