version: 2

models:
  - name: dim_customers
    description: "Customer dimension table with analytics"
    columns:
      - name: customer_id
        description: "Primary key for customer"
        tests:
          - unique
          - not_null
      - name: customer_tier
        description: "Customer tier based on wealth rank"
        tests:
          - accepted_values:
              arguments:
                values: ['Platinum', 'Gold', 'Silver', 'Bronze']  # ← Fixed syntax